# Triggered manually — picks up the image currently running in QA and opens
# a PR in the GitOps repo (vars.GITOPS_REPO) to promote it to PROD.
# PROD ArgoCD app manual deploy after merge.

name: Promote — Backend - QA - To - PROD

on:
  workflow_dispatch: 

permissions:
  contents: read
  id-token: write
  pull-requests: write

jobs:   

  oidc-debug:
    name: Debug GitHub OIDC Claims
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Show OIDC claims
        uses: github/actions-oidc-debugger@main
        
  promote-dev-to-qa:
    uses: vaheed-valaxy/central-github-actions/.github/workflows/reusable-promote-qa-to-prod.yml@main
    with:
      service-name: backend
      
      qa-values-file: envs/qa/values-backend.yaml
      prod-values-file: envs/prod/values-backend.yaml
      
      gitops-repo: shopverse-gitops
      gitops-owner: vaheed-valaxy
      
      qa-ecr-repo: shopverse-qa/backend
      prod-ecr-repo: shopverse/backend
      
      aws-region: us-east-1
      aws-ecr-prod-promotion-role-arn: ${{ vars.AWS_ECR_ROLE_ARN }} # arn:aws:iam::123456789012:role/shopverse-qa-promotion

      # cosign-certificate-identity-regexp:
      # cosign-oidc-issuer:
  
    secrets:
      GITOPS_TOKEN: ${{ secrets.GITOPS_TOKEN }}
